INSERT INTO hero (id, name, account_image) VALUES (1, 'Mr. Nice', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (2, 'Narco', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (3, 'Bombasto', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (4, 'Celeritas', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (5, 'Magneta', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (6, 'RubberMan', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (7, 'Dynama', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (8, 'Dr. IQ', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (9, 'Magma', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (10, 'Tornado', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (11, 'Roger', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (12, 'Nadal', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (13, 'Ferer', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (14, 'Andy', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (15, 'Kei', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (16, 'Kigrios', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (17, 'Wanrinka', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (18, 'Cilic', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (19, 'Del Potro', '/assets/images/default.jpeg');
INSERT INTO hero (id, name, account_image) VALUES (20, 'Mr. Nice', '/assets/images/default.jpeg');
